#!/usr/bin/env python3
"""
QGC (MAVLink) <-> OpenUxAS (LMCP/ZeroMQ) Bridge.

Wire-compatible with the OpenUxAS LmcpObjectNetworkPublishPullBridge:
    - Subscribes (ZMQ_SUB) to UxAS's external publish socket (default 5560).
    - Pushes (ZMQ_PUSH) to UxAS's external pull socket (default 5561).
    - Each datagram is an AddressedAttributedMessage single-part envelope:
        <address> '$' <contentType> '|' <descriptor> '|' <sourceGroup>
        '|' <sourceEntityId> '|' <sourceServiceId> '$' <LMCP binary payload>
      where the payload is the binary serialization produced by
      lmcp.LMCPFactory.packMessage(obj, calcChecksum=True).

The bridge:
    - Reads MAVLink telemetry from PX4/QGC and publishes AirVehicleConfiguration
      and AirVehicleState messages to UxAS at a configurable rate.
    - Receives MissionCommand from UxAS, converts each Waypoint to a MAVLink
      mission item, and uploads the mission to the vehicle.
    - Provides an interactive CLI to register vehicles and submit AreaSearchTask
      / LineSearchTask + AutomationRequest sequences.

Usage:
    python3 qgc_uxas_bridge.py --mavlink udp:127.0.0.1:14550 \\
        --uxas-pub tcp://127.0.0.1:5560 --uxas-pull tcp://127.0.0.1:5561 \\
        --vehicle-id 1 --auto-register
"""

from __future__ import annotations

import argparse
import cmd
import collections
import copy
import json
import math
import os
import signal
import socket
import sys
import textwrap
import threading
import time
from dataclasses import dataclass, field
from typing import Any, Callable, Optional

# --- Make sibling lmcp_py package importable regardless of CWD ---------------
_SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
_LMCP_PY_DIR = os.path.normpath(os.path.join(_SCRIPT_DIR, "..", "lmcp_py"))
if _LMCP_PY_DIR not in sys.path:
    sys.path.insert(0, _LMCP_PY_DIR)

try:
    from pymavlink import mavutil
except ImportError:
    print("ERROR: pymavlink is required. Install with: pip install pymavlink",
          file=sys.stderr)
    sys.exit(1)

try:
    import zmq
except ImportError:
    print("ERROR: pyzmq is required. Install with: pip install pyzmq",
          file=sys.stderr)
    sys.exit(1)

try:
    from lmcp import LMCPFactory  # generated by LmcpGen
    from afrl.cmasi.AirVehicleConfiguration import AirVehicleConfiguration
    from afrl.cmasi.AirVehicleState import AirVehicleState
    from afrl.cmasi.AreaSearchTask import AreaSearchTask
    from afrl.cmasi.LineSearchTask import LineSearchTask
    from afrl.cmasi.AutomationRequest import AutomationRequest
    from afrl.cmasi.Location3D import Location3D
    from afrl.cmasi.Polygon import Polygon
    from afrl.cmasi.FlightProfile import FlightProfile
    from afrl.cmasi.AltitudeType import AltitudeType
    from afrl.cmasi.NavigationMode import NavigationMode
    from afrl.cmasi.KeepInZone import KeepInZone
    from afrl.cmasi.KeepOutZone import KeepOutZone
    from afrl.cmasi.OperatingRegion import OperatingRegion
    from afrl.cmasi.GimbalConfiguration import GimbalConfiguration
    from afrl.cmasi.CameraConfiguration import CameraConfiguration
    from afrl.cmasi.GimballedPayloadState import GimballedPayloadState
    from afrl.cmasi.CameraState import CameraState
    from afrl.cmasi.WavelengthBand import WavelengthBand
    from afrl.cmasi.FOVOperationMode import FOVOperationMode
    from afrl.cmasi.GimbalPointingMode import GimbalPointingMode
except ImportError as exc:
    print(f"ERROR: Python LMCP library not found at {_LMCP_PY_DIR}.\n"
          f"Generate it with:\n"
          f"  java -jar LmcpGen.jar -mdmdir <OpenUxAS>/mdms -py -dir "
          f"{_LMCP_PY_DIR}\n"
          f"Detail: {exc}",
          file=sys.stderr)
    sys.exit(1)


# ---------------------------------------------------------------------------
# AddressedAttributedMessage envelope (single-part, '$' / '|' delimiters)
# ---------------------------------------------------------------------------

ADDR_DELIM = b"$"
FIELD_DELIM = b"|"


def encode_envelope(
    address: str,
    descriptor: str,
    source_group: str,
    entity_id: str,
    service_id: str,
    payload: bytes,
    content_type: str = "lmcp",
) -> bytes:
    """Build the single-part AddressedAttributedMessage wire form."""
    addr = address.encode("utf-8")
    attrs = FIELD_DELIM.join([
        content_type.encode("utf-8"),
        descriptor.encode("utf-8"),
        source_group.encode("utf-8"),
        entity_id.encode("utf-8"),
        service_id.encode("utf-8"),
    ])
    return addr + ADDR_DELIM + attrs + ADDR_DELIM + payload


@dataclass
class Envelope:
    address: str
    content_type: str
    descriptor: str
    source_group: str
    entity_id: str
    service_id: str
    payload: bytes


def decode_envelope(data: bytes) -> Optional[Envelope]:
    """Parse the wire-form envelope. The payload is binary-safe (may contain $)."""
    idx_addr = data.find(ADDR_DELIM)
    if idx_addr < 0:
        return None
    idx_attrs = data.find(ADDR_DELIM, idx_addr + 1)
    if idx_attrs < 0:
        return None

    address = data[:idx_addr].decode("utf-8", errors="replace")
    attrs_raw = data[idx_addr + 1:idx_attrs].decode("utf-8", errors="replace")
    payload = bytes(data[idx_attrs + 1:])

    parts = attrs_raw.split("|")
    while len(parts) < 5:
        parts.append("")
    return Envelope(
        address=address,
        content_type=parts[0],
        descriptor=parts[1],
        source_group=parts[2],
        entity_id=parts[3],
        service_id=parts[4],
        payload=payload,
    )


# ---------------------------------------------------------------------------
# Data structures
# ---------------------------------------------------------------------------

@dataclass
class VehicleState:
    """Latest vehicle state extracted from MAVLink."""
    vehicle_id: int = 1
    lat_deg: float = 0.0
    lon_deg: float = 0.0
    alt_m: float = 0.0
    alt_agl_m: float = 0.0   # GLOBAL_POSITION_INT.relative_alt (m above home)
    heading_deg: float = 0.0
    airspeed_mps: float = 0.0
    groundspeed_mps: float = 0.0
    climb_rate_mps: float = 0.0
    roll_deg: float = 0.0
    pitch_deg: float = 0.0
    yaw_deg: float = 0.0
    battery_pct: float = 100.0
    mode: str = "unknown"
    armed: bool = False
    timestamp_ms: int = 0
    gps_fix: int = 0          # GPS_RAW_INT.fix_type (>=3 → 3D fix)


@dataclass
class WaypointItem:
    """Single waypoint distilled from an LMCP MissionCommand."""
    seq: int = 0
    lat_deg: float = 0.0
    lon_deg: float = 0.0
    alt_m: float = 50.0
    speed_mps: float = 15.0
    turn_type: str = "TurnShort"


@dataclass
class BridgeStats:
    """Counters for bridge activity."""
    mavlink_msgs_in: int = 0
    mavlink_msgs_out: int = 0
    lmcp_msgs_in: int = 0
    lmcp_msgs_out: int = 0
    missions_uploaded: int = 0
    errors: int = 0
    start_time: float = field(default_factory=time.monotonic)


# ---------------------------------------------------------------------------
# LMCP message builders
# ---------------------------------------------------------------------------

def _location3d(lat: float, lon: float, alt: float,
                alt_type: int = AltitudeType.MSL) -> Location3D:
    loc = Location3D()
    loc.set_Latitude(lat)
    loc.set_Longitude(lon)
    loc.set_Altitude(alt)
    loc.set_AltitudeType(alt_type)
    return loc


def gimbal_payload_id(vehicle_id: int) -> int:
    """Convention: gimbal PayloadID = 100*vehicle_id + 1."""
    return 100 * vehicle_id + 1


def camera_payload_id(vehicle_id: int) -> int:
    """Convention: camera PayloadID = 100*vehicle_id + 2."""
    return 100 * vehicle_id + 2


def build_gimbal_configuration(vehicle_id: int,
                               camera_payload_ids: list[int]) -> GimbalConfiguration:
    """EO standard gimbal: free pan/tilt, no roll, 30 deg/s slew."""
    g = GimbalConfiguration()
    g.set_PayloadID(gimbal_payload_id(vehicle_id))
    g.SupportedPointingModes.append(GimbalPointingMode.AirVehicleRelativeAngle)
    g.SupportedPointingModes.append(GimbalPointingMode.LatLonSlaved)
    g.set_MinAzimuth(-180.0); g.set_MaxAzimuth(180.0)
    g.set_MinElevation(-180.0); g.set_MaxElevation(180.0)
    g.set_MinRotation(0.0); g.set_MaxRotation(0.0)
    g.set_IsAzimuthClamped(False)
    g.set_IsElevationClamped(False)
    g.set_IsRotationClamped(True)
    g.set_MaxAzimuthSlewRate(30.0)
    g.set_MaxElevationSlewRate(30.0)
    g.set_MaxRotationRate(0.0)
    for cid in camera_payload_ids:
        g.ContainedPayloadList.append(cid)
    return g


def build_camera_configuration(vehicle_id: int) -> CameraConfiguration:
    """EO visible-band camera with discrete variable-zoom FoV (examples preset)."""
    c = CameraConfiguration()
    c.set_PayloadID(camera_payload_id(vehicle_id))
    c.set_SupportedWavelengthBand(WavelengthBand.EO)
    c.set_FieldOfViewMode(FOVOperationMode.Discrete)
    c.set_MinHorizontalFieldOfView(0.11)
    c.set_MaxHorizontalFieldOfView(45.0)
    for fov in (45.0, 22.0, 7.6, 3.7, 0.63, 0.11):
        c.DiscreteHorizontalFieldOfViewList.append(fov)
    c.set_VideoStreamHorizontalResolution(1024)
    c.set_VideoStreamVerticalResolution(768)
    return c


def build_air_vehicle_configuration(
    vehicle_id: int,
    label: str = "UAV",
    min_speed: float = 5.0,
    max_speed: float = 30.0,
    nominal_speed: Optional[float] = None,
    nominal_altitude: float = 100.0,
    max_climb: float = 5.0,
    min_alt: float = 0.0,
    max_alt: float = 500.0,
    max_bank_deg: float = 25.0,
    include_payload: bool = True,
) -> AirVehicleConfiguration:
    nominal_speed = nominal_speed if nominal_speed is not None \
        else (min_speed + max_speed) / 2.0

    fp = FlightProfile()
    fp.set_Name("Cruise")
    fp.set_Airspeed(nominal_speed)
    fp.set_PitchAngle(0.0)
    fp.set_VerticalSpeed(0.0)
    fp.set_MaxBankAngle(max_bank_deg)
    fp.set_EnergyRate(0.02)

    avc = AirVehicleConfiguration()
    avc.set_ID(vehicle_id)
    avc.set_Label(label)
    avc.set_MinimumSpeed(min_speed)
    avc.set_MaximumSpeed(max_speed)
    avc.set_NominalSpeed(nominal_speed)
    avc.set_MinimumAltitude(min_alt)
    avc.set_MinAltitudeType(AltitudeType.MSL)
    avc.set_MaximumAltitude(max_alt)
    avc.set_MaxAltitudeType(AltitudeType.MSL)
    avc.set_NominalAltitude(nominal_altitude)
    avc.set_NominalAltitudeType(AltitudeType.MSL)
    avc.set_NominalFlightProfile(fp)

    if include_payload:
        cam = build_camera_configuration(vehicle_id)
        gim = build_gimbal_configuration(
            vehicle_id, camera_payload_ids=[cam.get_PayloadID()])
        avc.PayloadConfigurationList.append(cam)
        avc.PayloadConfigurationList.append(gim)
    return avc


def build_air_vehicle_state(state: VehicleState,
                            include_payload: bool = True) -> AirVehicleState:
    avs = AirVehicleState()
    avs.set_ID(state.vehicle_id)
    avs.set_Time(state.timestamp_ms or int(time.time() * 1000))

    avs.set_Location(_location3d(state.lat_deg, state.lon_deg, state.alt_m))
    avs.set_Heading(state.heading_deg)
    avs.set_Course(state.heading_deg)
    avs.set_Airspeed(state.airspeed_mps)
    avs.set_Groundspeed(state.groundspeed_mps)
    avs.set_VerticalSpeed(state.climb_rate_mps)
    avs.set_Pitch(state.pitch_deg)
    avs.set_Roll(state.roll_deg)
    # CMASI uses heading as compass bearing; yaw goes into the chosen field
    avs.set_EnergyAvailable(state.battery_pct)
    avs.set_ActualEnergyRate(0.0)
    avs.set_Mode(NavigationMode.Waypoint)
    avs.set_CurrentWaypoint(0)

    if include_payload:
        # Camera state (level, FoV 20°, no footprint yet — UxAS computes it)
        cam = CameraState()
        cam.set_PayloadID(camera_payload_id(state.vehicle_id))
        cam.set_PointingMode(GimbalPointingMode.AirVehicleRelativeAngle)
        cam.set_Azimuth(0.0); cam.set_Elevation(-90.0)  # nadir
        _fov = _camera_fov_now(state.vehicle_id)              # per-vehicle (SAR) or shared panel FOV
        cam.set_HorizontalFieldOfView(_fov)
        cam.set_VerticalFieldOfView(_fov * 0.75)
        # Gimbal state (mirrors camera pointing)
        gim = GimballedPayloadState()
        gim.set_PayloadID(gimbal_payload_id(state.vehicle_id))
        gim.set_PointingMode(GimbalPointingMode.AirVehicleRelativeAngle)
        gim.set_Azimuth(0.0); gim.set_Elevation(-90.0); gim.set_Rotation(0.0)
        avs.PayloadStateList.append(cam)
        avs.PayloadStateList.append(gim)

    return avs


def build_area_search_task(
    task_id: int,
    polygon_lat_lon: list[tuple[float, float]],
    eligible_vehicles: list[int],
    altitude_m: float = 50.0,
    label: str = "AreaSearch",
) -> AreaSearchTask:
    poly = Polygon()
    for lat, lon in polygon_lat_lon:
        poly.BoundaryPoints.append(_location3d(lat, lon, altitude_m))

    task = AreaSearchTask()
    task.set_TaskID(task_id)
    task.set_Label(label)
    task.set_SearchArea(poly)
    for vid in eligible_vehicles:
        task.EligibleEntities.append(vid)
    return task


def build_line_search_task(
    task_id: int,
    line_lat_lon: list[tuple[float, float]],
    eligible_vehicles: list[int],
    altitude_m: float = 50.0,
    label: str = "LineSearch",
) -> LineSearchTask:
    task = LineSearchTask()
    task.set_TaskID(task_id)
    task.set_Label(label)
    for lat, lon in line_lat_lon:
        task.PointList.append(_location3d(lat, lon, altitude_m))
    for vid in eligible_vehicles:
        task.EligibleEntities.append(vid)
    return task


def build_automation_request(
    request_id: int,
    task_ids: list[int],
    vehicle_ids: list[int],
    operating_region: int = 0,
    redo_all: bool = False,
) -> AutomationRequest:
    req = AutomationRequest()
    req.set_OperatingRegion(operating_region)
    req.set_RedoAllTasks(redo_all)
    for tid in task_ids:
        req.TaskList.append(tid)
    for vid in vehicle_ids:
        req.EntityList.append(vid)
    return req


# Camera horizontal FOV (deg) used in the streamed AirVehicleState — UxAS reads
# this to size the sensor footprint and thus the AreaSearch lane spacing. Kept in
# sync with the QGC panel's Sensor/FOV via a shared file the search listener
# writes (uxas_search_listener writes the published "fov" to _FOV_FILE). We read
# it here rather than binding the EventBroadcaster port — binding 45678 in every
# bridge would steal publishes from the listener (SO_REUSEPORT load-balancing).
_CAMERA_FOV = [45.0]
_FOV_FILE = "/tmp/uxas_camera_fov.txt"


def _camera_fov_now(vid=None) -> float:
    """Current camera FOV (deg) for the streamed AirVehicleState. Prefers a
    per-vehicle file (/tmp/uxas_camera_fov_<vid>.txt — written by SAR tasking so
    fixed-wing and multicopter can use different FOVs), then the shared file, then
    the bridge's --camera-fov default."""
    paths = []
    if vid is not None:
        paths.append(f"/tmp/uxas_camera_fov_{vid}.txt")
    paths.append(_FOV_FILE)
    for p in paths:
        try:
            with open(p) as fh:
                fov = float(fh.read().strip())
            if 1.0 <= fov <= 120.0:
                return fov
        except (OSError, ValueError):
            continue
    return _CAMERA_FOV[0]


def _bearing_deg(lat1: float, lon1: float, lat2: float, lon2: float) -> float:
    """Initial great-circle bearing from point 1 to point 2, degrees 0..360
    (0 = North, 90 = East). Used to yaw a waypoint toward the next one."""
    phi1, phi2 = math.radians(lat1), math.radians(lat2)
    dlon = math.radians(lon2 - lon1)
    y = math.sin(dlon) * math.cos(phi2)
    x = (math.cos(phi1) * math.sin(phi2)
         - math.sin(phi1) * math.cos(phi2) * math.cos(dlon))
    return (math.degrees(math.atan2(y, x)) + 360.0) % 360.0


def _meters_to_lat(m: float) -> float:
    """Approximate meters → degrees of latitude (constant)."""
    return m / 111320.0


def _meters_to_lon(m: float, lat_deg: float) -> float:
    """Approximate meters → degrees of longitude at the given latitude."""
    import math
    return m / (111320.0 * max(math.cos(math.radians(lat_deg)), 1e-6))


def build_keep_in_zone(
    zone_id: int,
    center_lat: float,
    center_lon: float,
    half_size_m: float = 2000.0,
    min_alt_m: float = 0.0,
    max_alt_m: float = 500.0,
    label: str = "KeepIn",
) -> KeepInZone:
    """Build a rectangular KeepInZone centered on (lat, lon).

    The zone is a 4-vertex Polygon spanning ±half_size_m east/west and
    north/south of the center, with altitude band [min_alt_m, max_alt_m]
    (MSL).
    """
    dlat = _meters_to_lat(half_size_m)
    dlon = _meters_to_lon(half_size_m, center_lat)
    poly = Polygon()
    for lat, lon in [(center_lat - dlat, center_lon - dlon),
                     (center_lat - dlat, center_lon + dlon),
                     (center_lat + dlat, center_lon + dlon),
                     (center_lat + dlat, center_lon - dlon)]:
        poly.BoundaryPoints.append(_location3d(lat, lon, max_alt_m))

    z = KeepInZone()
    z.set_ZoneID(zone_id)
    z.set_Label(label)
    z.set_MinAltitude(min_alt_m)
    z.set_MinAltitudeType(AltitudeType.MSL)
    z.set_MaxAltitude(max_alt_m)
    z.set_MaxAltitudeType(AltitudeType.MSL)
    z.set_Boundary(poly)
    return z


def build_operating_region(
    region_id: int,
    keep_in_ids: list[int],
    keep_out_ids: Optional[list[int]] = None,
) -> OperatingRegion:
    """Build an OperatingRegion referencing existing KeepIn/KeepOut Zone IDs."""
    region = OperatingRegion()
    region.set_ID(region_id)
    for zid in keep_in_ids:
        region.KeepInAreas.append(zid)
    for zid in (keep_out_ids or []):
        region.KeepOutAreas.append(zid)
    return region


def waypoints_from_mission_command(mc) -> list[WaypointItem]:
    """Extract waypoints from an LMCP MissionCommand object."""
    items: list[WaypointItem] = []
    for i, wp in enumerate(mc.get_WaypointList()):
        try:
            turn = str(wp.get_TurnType())
        except Exception:
            turn = "TurnShort"
        items.append(WaypointItem(
            seq=i,
            lat_deg=wp.get_Latitude(),
            lon_deg=wp.get_Longitude(),
            alt_m=wp.get_Altitude(),
            speed_mps=wp.get_Speed(),
            turn_type=turn,
        ))
    return items


# ---------------------------------------------------------------------------
# MAVLink reader thread
# ---------------------------------------------------------------------------

class MAVLinkReader:
    """Reads MAVLink messages and updates vehicle state.

    The single mavutil connection is shared by the telemetry _read_loop and
    by upload_mission()/arm()/set_mode(). When a control method needs to
    receive specific protocol messages (MISSION_REQUEST, COMMAND_ACK, ...),
    it sets ``_capture_types`` and the _read_loop routes matching frames into
    ``_capture_queue`` instead of consuming them. Otherwise we hit the classic
    pymavlink race: both threads call recv() on the same socket and one
    silently drops the protocol replies.
    """

    def __init__(self, connection_str: str, vehicle_id: int = 1,
                 require_heartbeat: bool = True):
        self.connection_str = connection_str
        self.vehicle_id = vehicle_id
        self._require_heartbeat = require_heartbeat
        self.conn: Optional[Any] = None
        self.state = VehicleState(vehicle_id=vehicle_id)
        self._lock = threading.Lock()
        self._running = False
        self._thread: Optional[threading.Thread] = None
        self.stats = BridgeStats()
        self._capture_types: set[str] = set()
        self._capture_queue: "collections.deque[Any]" = collections.deque(maxlen=64)
        self._capture_lock = threading.Lock()
        self._control_lock = threading.Lock()  # serializes arm/set_mode/upload
        self._hb_thread: Optional[threading.Thread] = None
        self._last_mission_current: tuple = ()

    def start(self) -> None:
        print(f"[MAVLink] Connecting to {self.connection_str} ...")
        self.conn = mavutil.mavlink_connection(self.connection_str)
        if self._require_heartbeat:
            self.conn.wait_heartbeat(timeout=30)
            print(f"[MAVLink] Heartbeat received "
                  f"(system {self.conn.target_system}, "
                  f"component {self.conn.target_component})")
        else:
            print("[MAVLink] Skipping heartbeat wait (offline test mode)")
        self._running = True
        self._thread = threading.Thread(target=self._read_loop, daemon=True,
                                        name="mavlink-reader")
        self._thread.start()
        # PX4 refuses to arm ("Resolve system health failures first") until it
        # sees a GCS heartbeat on the link. Send one at 1 Hz so the bridge is
        # recognized as a connected GCS.
        self._hb_thread = threading.Thread(target=self._heartbeat_loop,
                                           daemon=True, name="gcs-heartbeat")
        self._hb_thread.start()

    def _heartbeat_loop(self) -> None:
        while self._running:
            try:
                if self.conn:
                    # MAV_TYPE_GCS=6, MAV_AUTOPILOT_INVALID=8
                    self.conn.mav.heartbeat_send(6, 8, 0, 0, 0)
            except Exception:
                pass
            time.sleep(1.0)

    def stop(self) -> None:
        self._running = False
        if self._thread:
            self._thread.join(timeout=3)
        if self._hb_thread:
            self._hb_thread.join(timeout=3)
        if self.conn:
            try:
                self.conn.close()
            except Exception:
                pass

    def get_state(self) -> VehicleState:
        with self._lock:
            return copy.copy(self.state)

    # -- capture helpers ------------------------------------------------------

    def _wait_capture(self, types: list[str], timeout: float) -> Optional[Any]:
        """Wait for a message of one of *types* that _read_loop captured."""
        deadline = time.monotonic() + timeout
        while time.monotonic() < deadline:
            with self._capture_lock:
                for idx, msg in enumerate(self._capture_queue):
                    if msg.get_type() in types:
                        del self._capture_queue[idx]
                        return msg
            time.sleep(0.02)
        return None

    def _start_capture(self, types: list[str]) -> None:
        with self._capture_lock:
            self._capture_types = set(types)
            self._capture_queue.clear()

    def _stop_capture(self) -> None:
        with self._capture_lock:
            self._capture_types = set()
            self._capture_queue.clear()

    # -- control commands -----------------------------------------------------

    def upload_mission(self, items: list[dict]) -> bool:
        if not self.conn:
            return False
        print(f"[MAVLink] Uploading {len(items)} mission items ...")
        with self._control_lock:
            self._start_capture(["MISSION_REQUEST", "MISSION_REQUEST_INT",
                                 "MISSION_ACK"])
            try:
                self.conn.waypoint_clear_all_send()
                time.sleep(0.3)
                # Drain stray pre-handshake ACK if any.
                _ = self._wait_capture(["MISSION_ACK"], 0.2)
                self.conn.waypoint_count_send(len(items))

                for i in range(len(items)):
                    msg = self._wait_capture(
                        ["MISSION_REQUEST", "MISSION_REQUEST_INT"], 10.0)
                    if msg is None:
                        print(f"[MAVLink] Timeout waiting for "
                              f"MISSION_REQUEST (item {i})")
                        self.stats.errors += 1
                        return False
                    item = items[msg.seq] if msg.seq < len(items) else items[i]
                    self.conn.mav.mission_item_int_send(
                        self.conn.target_system,
                        self.conn.target_component,
                        msg.seq,
                        item.get("frame", 6),
                        item.get("command", 16),
                        1 if msg.seq == 0 else 0,
                        int(item.get("autocontinue", 1)),
                        item.get("param1", 0),
                        item.get("param2", 5.0),
                        item.get("param3", 0),
                        item.get("param4", 0),
                        int(item["lat"] * 1e7),
                        int(item["lon"] * 1e7),
                        item.get("alt", 50),
                    )

                ack = self._wait_capture(["MISSION_ACK"], 10.0)
                if ack and ack.type == 0:
                    self.stats.missions_uploaded += 1
                    self.stats.mavlink_msgs_out += len(items)
                    print("[MAVLink] Mission upload complete")
                    return True
                print(f"[MAVLink] Mission upload failed (ack={ack})")
                self.stats.errors += 1
                return False
            finally:
                self._stop_capture()

    def arm(self, arm_flag: bool = True, force: bool = False,
            timeout: float = 5.0) -> bool:
        """Send MAV_CMD_COMPONENT_ARM_DISARM and wait for COMMAND_ACK."""
        if not self.conn:
            return False
        param1 = 1.0 if arm_flag else 0.0
        param2 = 21196.0 if force else 0.0  # PX4 magic-number force flag
        with self._control_lock:
            self._start_capture(["COMMAND_ACK"])
            try:
                self.conn.mav.command_long_send(
                    self.conn.target_system, self.conn.target_component,
                    400,  # MAV_CMD_COMPONENT_ARM_DISARM
                    0,
                    param1, param2, 0, 0, 0, 0, 0)
                deadline = time.monotonic() + timeout
                while time.monotonic() < deadline:
                    ack = self._wait_capture(["COMMAND_ACK"], 0.5)
                    if ack is None:
                        continue
                    if ack.command == 400:
                        ok = (ack.result == 0)
                        print(f"[MAVLink] ARM={arm_flag} ack result={ack.result}"
                              f" ({'OK' if ok else 'FAIL'})")
                        return ok
            finally:
                self._stop_capture()
        return False

    def takeoff(self, target_alt_agl_m: float, timeout: float = 5.0) -> bool:
        """Send MAV_CMD_NAV_TAKEOFF to climb *target_alt_agl_m* metres AGL.

        IMPORTANT: PX4 interprets command_long NAV_TAKEOFF param7 as an
        ABSOLUTE AMSL altitude, not AGL. We convert by adding the home AMSL
        altitude derived from the current state (alt_m is AMSL, alt_agl_m is
        relative), so the vehicle actually climbs the requested AGL amount.
        PX4 auto-switches to AUTO.TAKEOFF on receipt.
        """
        if not self.conn:
            return False
        s = self.get_state()
        home_amsl = s.alt_m - s.alt_agl_m   # ground AMSL
        target_amsl = home_amsl + target_alt_agl_m
        # CRITICAL: lat/lon MUST be the current position. Sending 0,0 makes PX4
        # plan a takeoff toward the equator (0,0) — the controller then refuses
        # to spin the motors and the vehicle auto-disarms without lifting.
        cur_lat = s.lat_deg
        cur_lon = s.lon_deg
        with self._control_lock:
            self._start_capture(["COMMAND_ACK"])
            try:
                print(f"[MAVLink] TAKEOFF target {target_alt_agl_m:.0f}m AGL "
                      f"= {target_amsl:.0f}m AMSL (home {home_amsl:.0f}m) "
                      f"@ ({cur_lat:.6f},{cur_lon:.6f})")
                self.conn.mav.command_long_send(
                    self.conn.target_system, self.conn.target_component,
                    22,  # MAV_CMD_NAV_TAKEOFF
                    0,
                    0,    # param1: minimum pitch
                    0,    # param2: empty
                    0,    # param3: empty
                    float('nan'),  # param4: yaw (NaN = keep current)
                    cur_lat, cur_lon,   # current position (NOT 0,0)
                    float(target_amsl),
                )
                deadline = time.monotonic() + timeout
                while time.monotonic() < deadline:
                    ack = self._wait_capture(["COMMAND_ACK"], 0.5)
                    if ack is None:
                        continue
                    if ack.command == 22:
                        ok = (ack.result == 0)
                        print(f"[MAVLink] TAKEOFF agl={target_alt_agl_m:.0f}m "
                              f"ack={ack.result} ({'OK' if ok else 'FAIL'})")
                        return ok
                print(f"[MAVLink] TAKEOFF timed out")
                return False
            finally:
                self._stop_capture()

    def set_param(self, name: str, value: float,
                  timeout: float = 3.0) -> bool:
        """Set a PX4 parameter via PARAM_SET and wait for the PARAM_VALUE echo.

        Needed because launch_all.sh only consumes SYS_AUTOSTART from
        vehicles.json "parameters" — everything else must be applied over
        MAVLink after boot (e.g. MIS_TKO_LAND_REQ=0 so UxAS waypoint-only
        missions pass the fixed-wing feasibility check).

        PX4 rejects PARAM_SET whose param_type does not match the parameter's
        declared type, so we PARAM_REQUEST_READ first to learn the real type
        (guessing INT32 from "10" silently fails on FLOAT params).
        """
        if not self.conn:
            return False
        with self._control_lock:
            self._start_capture(["PARAM_VALUE"])
            try:
                # 1) Learn the parameter's declared type.
                self.conn.mav.param_request_read_send(
                    self.conn.target_system, self.conn.target_component,
                    name.encode(), -1)
                ptype = None
                deadline = time.monotonic() + timeout
                while time.monotonic() < deadline:
                    msg = self._wait_capture(["PARAM_VALUE"], 0.5)
                    if msg is not None and msg.param_id == name:
                        ptype = msg.param_type
                        break
                if ptype is None:
                    print(f"[MAVLink] PARAM {name} not found (read timeout)")
                    return False
                # 2) Set with the matching type (PX4 by-value convention).
                self.conn.mav.param_set_send(
                    self.conn.target_system, self.conn.target_component,
                    name.encode(), float(value), ptype)
                deadline = time.monotonic() + timeout
                while time.monotonic() < deadline:
                    msg = self._wait_capture(["PARAM_VALUE"], 0.5)
                    if msg is not None and msg.param_id == name:
                        print(f"[MAVLink] PARAM {name} = "
                              f"{msg.param_value:g} (OK)")
                        return True
                print(f"[MAVLink] PARAM {name} set timed out")
                return False
            finally:
                self._stop_capture()

    def set_mode_auto_mission(self, timeout: float = 5.0) -> bool:
        """Switch PX4 to AUTO.MISSION (main_mode=4, sub_mode=4)."""
        if not self.conn:
            return False
        # PX4 custom mode encoding: high bits = main_mode, sub_mode
        # MAIN_MODE_AUTO=4, SUB_MODE_AUTO_MISSION=4
        custom_mode = (4 << 16) | (4 << 24)
        base_mode = 1  # MAV_MODE_FLAG_CUSTOM_MODE_ENABLED
        with self._control_lock:
            self._start_capture(["COMMAND_ACK", "HEARTBEAT"])
            try:
                self.conn.mav.command_long_send(
                    self.conn.target_system, self.conn.target_component,
                    176,  # MAV_CMD_DO_SET_MODE
                    0,
                    base_mode, 4, 4, 0, 0, 0, 0)
                deadline = time.monotonic() + timeout
                while time.monotonic() < deadline:
                    msg = self._wait_capture(["COMMAND_ACK", "HEARTBEAT"], 0.5)
                    if msg is None:
                        continue
                    if msg.get_type() == "COMMAND_ACK" and msg.command == 176:
                        ok = (msg.result == 0)
                        print(f"[MAVLink] AUTO.MISSION ack result={msg.result}"
                              f" ({'OK' if ok else 'FAIL'})")
                        return ok
                print("[MAVLink] AUTO.MISSION switch timed out")
                return False
            finally:
                self._stop_capture()

    def _read_loop(self) -> None:
        while self._running:
            try:
                msg = self.conn.recv_match(blocking=True, timeout=0.5)
                if msg is None:
                    continue
                mtype = msg.get_type()
                # Route protocol replies to whichever control method is waiting.
                with self._capture_lock:
                    if self._capture_types and mtype in self._capture_types:
                        self._capture_queue.append(msg)
                        continue
                with self._lock:
                    self.stats.mavlink_msgs_in += 1
                    if mtype == "GLOBAL_POSITION_INT":
                        self.state.lat_deg = msg.lat / 1e7
                        self.state.lon_deg = msg.lon / 1e7
                        self.state.alt_m = msg.alt / 1e3
                        self.state.alt_agl_m = msg.relative_alt / 1e3
                        self.state.heading_deg = msg.hdg / 100.0
                        self.state.climb_rate_mps = -msg.vz / 100.0
                        self.state.groundspeed_mps = math.sqrt(
                            (msg.vx / 100.0) ** 2 + (msg.vy / 100.0) ** 2)
                        self.state.timestamp_ms = int(time.time() * 1000)
                    elif mtype == "GPS_RAW_INT":
                        self.state.gps_fix = msg.fix_type
                    elif mtype == "ATTITUDE":
                        self.state.roll_deg = math.degrees(msg.roll)
                        self.state.pitch_deg = math.degrees(msg.pitch)
                        self.state.yaw_deg = math.degrees(msg.yaw)
                    elif mtype == "VFR_HUD":
                        self.state.airspeed_mps = msg.airspeed
                        self.state.groundspeed_mps = msg.groundspeed
                    elif mtype == "SYS_STATUS":
                        if msg.battery_remaining >= 0:
                            self.state.battery_pct = float(msg.battery_remaining)
                    elif mtype == "HEARTBEAT":
                        self.state.armed = bool(
                            msg.base_mode
                            & mavutil.mavlink.MAV_MODE_FLAG_SAFETY_ARMED)
                        custom = msg.custom_mode
                        main_mode = (custom >> 16) & 0xFF
                        sub_mode = (custom >> 24) & 0xFF
                        mode_map = {
                            (1, 0): "manual",
                            (2, 0): "posctl",
                            (4, 1): "auto_ready",
                            (4, 2): "auto_takeoff",
                            (4, 3): "auto_loiter",
                            (4, 4): "auto_mission",
                            (4, 5): "auto_rtl",
                            (4, 6): "auto_land",
                            (6, 0): "offboard",
                        }
                        self.state.mode = mode_map.get(
                            (main_mode, sub_mode),
                            f"custom({main_mode},{sub_mode})")
                    elif mtype == "STATUSTEXT":
                        # PX4 explains mission rejections / warnings here —
                        # essential when AUTO.MISSION silently falls back to
                        # LOITER (e.g. feasibility check failures).
                        print(f"[PX4:{self.vehicle_id}] {msg.text}")
                    elif mtype == "MISSION_CURRENT":
                        # mission_state: 1=NO_MISSION 2=NOT_STARTED 3=ACTIVE
                        #                4=PAUSED 5=COMPLETE
                        cur = (msg.seq, getattr(msg, "mission_state", 0),
                               getattr(msg, "total", 0))
                        if cur != self._last_mission_current:
                            self._last_mission_current = cur
                            print(f"[PX4:{self.vehicle_id}] MISSION_CURRENT "
                                  f"seq={cur[0]} state={cur[1]} total={cur[2]}")
            except Exception as exc:
                if self._running:
                    print(f"[MAVLink] Read error: {exc}")
                    time.sleep(0.5)


# ---------------------------------------------------------------------------
# Monitor tap — fire-and-forget UDP JSON for QGC's MessageMonitor panel.
# ---------------------------------------------------------------------------

def _summarise_lmcp(obj: Any) -> str:
    """Return a one-line "key=val ..." summary of an LMCP object.

    Best-effort — pulls a handful of well-known fields (VehicleID, TaskID,
    Latitude/Longitude, Altitude, CommandID, …) so the QGC monitor row stays
    short. Never raises; falls back to the type name.
    """
    if obj is None:
        return ""
    name = type(obj).__name__
    pieces = [name]
    accessor_keys = [
        ("vid",   "get_VehicleID"),
        ("task",  "get_TaskID"),
        ("cmd",   "get_CommandID"),
        ("req",   "get_RequestID"),
        ("mode",  "get_Mode"),
        ("alt",   "get_Altitude"),
        ("speed", "get_Speed"),
    ]
    for label, fn in accessor_keys:
        try:
            getter = getattr(obj, fn, None)
            if getter is None:
                continue
            val = getter()
            if val is None:
                continue
            if isinstance(val, float):
                pieces.append(f"{label}={val:.2f}")
            else:
                pieces.append(f"{label}={val}")
        except Exception:
            pass
    # Location summary for AirVehicleState etc.
    try:
        loc_getter = getattr(obj, "get_Location", None)
        if loc_getter is not None:
            loc = loc_getter()
            if loc is not None:
                pieces.append(f"lat={loc.get_Latitude():.5f}")
                pieces.append(f"lon={loc.get_Longitude():.5f}")
    except Exception:
        pass
    return " ".join(pieces)[:160]


class MonitorTap:
    """Send a one-line JSON summary per LMCP/MAVLink event to QGC's monitor port.

    Used by qgc_uxas_bridge.py so QGC's MessageMonitorPage (UDP 45680 listener)
    can show *every* LMCP message the bridge handles, in real time, without
    needing a control connection back to the bridge. Best-effort — silently
    drops if the socket is full or QGC isn't listening.
    """

    def __init__(self, host: str = "127.0.0.1", port: int = 45680,
                 vehicle_id: int = 0):
        self.host = host
        self.port = port
        self.vehicle_id = vehicle_id
        self._enabled = port > 0
        self._sock: Optional[socket.socket] = None
        self._lock = threading.Lock()
        if self._enabled:
            try:
                self._sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
                self._sock.setblocking(False)
            except OSError as exc:
                print(f"[MonitorTap] disable: socket() failed: {exc}")
                self._enabled = False

    def close(self) -> None:
        with self._lock:
            if self._sock is not None:
                try:
                    self._sock.close()
                except OSError:
                    pass
                self._sock = None

    def emit(self, direction: str, lmcp_type: str, summary: str,
             extra: Optional[dict] = None) -> None:
        """Send a tap datagram.

        @param direction  "uxas_out", "uxas_in", "mavlink_out", "mavlink_in"
        @param lmcp_type  Short type name (e.g. "AirVehicleState") or ""
        @param summary    One-line summary string with key params (cheap)
        @param extra      Optional dict merged into payload
        """
        if not self._enabled or self._sock is None:
            return
        msg = {
            "ts": time.time(),
            "dir": direction,
            "lmcp_type": lmcp_type,
            "summary": summary,
            "vehicle_id": self.vehicle_id,
        }
        if extra:
            msg.update(extra)
        try:
            data = json.dumps(msg, separators=(",", ":")).encode("utf-8")
            with self._lock:
                if self._sock is not None:
                    self._sock.sendto(data, (self.host, self.port))
        except (OSError, ValueError):
            pass  # never let monitor disruption take down the bridge


# ---------------------------------------------------------------------------
# UxAS ZeroMQ interface (SUB on PUB endpoint, PUSH on PULL endpoint)
# ---------------------------------------------------------------------------

class UxASInterface:
    """Talks to OpenUxAS LmcpObjectNetworkPublishPullBridge.

    UxAS exposes an external PUB socket (we SUB to it) and an external PULL
    socket (we PUSH to it). Each datagram is an AddressedAttributedMessage
    single-part envelope wrapping an LMCP binary payload.
    """

    def __init__(self, sub_addr: str, push_addr: str,
                 entity_id: int, service_id: int = 0,
                 source_group: str = "",
                 monitor: Optional["MonitorTap"] = None):
        self.sub_addr = sub_addr
        self.push_addr = push_addr
        self.entity_id_str = str(entity_id)
        self.service_id_str = str(service_id)
        self.source_group = source_group
        self.monitor = monitor

        self.ctx: Optional[zmq.Context] = None
        self.sub_socket: Optional[zmq.Socket] = None
        self.push_socket: Optional[zmq.Socket] = None
        self._running = False
        self._thread: Optional[threading.Thread] = None
        self._lock = threading.Lock()
        self._callbacks: list[Callable[[Envelope, Any], None]] = []
        self._recent_messages: list[tuple[str, str]] = []  # (descriptor, summary)
        self._factory = LMCPFactory.LMCPFactory()
        self.stats = BridgeStats()

    def start(self) -> None:
        self.ctx = zmq.Context.instance()

        self.sub_socket = self.ctx.socket(zmq.SUB)
        self.sub_socket.connect(self.sub_addr)
        self.sub_socket.setsockopt_string(zmq.SUBSCRIBE, "")
        print(f"[UxAS] SUB connected to {self.sub_addr} "
              f"(receives from UxAS PUB)")

        self.push_socket = self.ctx.socket(zmq.PUSH)
        self.push_socket.connect(self.push_addr)
        print(f"[UxAS] PUSH connected to {self.push_addr} "
              f"(sends into UxAS PULL)")

        self._running = True
        self._thread = threading.Thread(target=self._receive_loop, daemon=True,
                                        name="uxas-receiver")
        self._thread.start()

    def stop(self) -> None:
        self._running = False
        if self._thread:
            self._thread.join(timeout=3)
        for sock in (self.sub_socket, self.push_socket):
            if sock is not None:
                try:
                    sock.close(linger=0)
                except Exception:
                    pass

    def publish(self, lmcp_obj) -> None:
        """Pack an LMCP object into binary, wrap in envelope, push to UxAS."""
        if self.push_socket is None:
            print("[UxAS] PUSH socket not connected -- drop message")
            return
        descriptor = lmcp_obj.FULL_LMCP_TYPE_NAME
        # CMASI broadcast pattern: address == descriptor
        payload = bytes(LMCPFactory.packMessage(lmcp_obj, True))
        envelope = encode_envelope(
            address=descriptor,
            descriptor=descriptor,
            source_group=self.source_group,
            entity_id=self.entity_id_str,
            service_id=self.service_id_str,
            payload=payload,
        )
        self.push_socket.send(envelope)
        with self._lock:
            self.stats.lmcp_msgs_out += 1
        if self.monitor is not None:
            self.monitor.emit("uxas_out",
                              type(lmcp_obj).__name__,
                              _summarise_lmcp(lmcp_obj),
                              extra={"descriptor": descriptor})

    def on_message(self, callback: Callable[[Envelope, Any], None]) -> None:
        """Register a callback (envelope, decoded_lmcp_obj_or_None)."""
        self._callbacks.append(callback)

    def get_recent(self, n: int = 10) -> list[tuple[str, str]]:
        with self._lock:
            return list(self._recent_messages[-n:])

    def _receive_loop(self) -> None:
        poller = zmq.Poller()
        poller.register(self.sub_socket, zmq.POLLIN)
        while self._running:
            try:
                socks = dict(poller.poll(timeout=500))
                if self.sub_socket in socks:
                    raw = self.sub_socket.recv()
                    env = decode_envelope(raw)
                    if env is None:
                        continue
                    obj = None
                    try:
                        if env.payload:
                            obj = self._factory.getObject(bytearray(env.payload))
                    except Exception as exc:
                        print(f"[UxAS] LMCP decode error for "
                              f"{env.descriptor}: {exc}")
                    with self._lock:
                        self.stats.lmcp_msgs_in += 1
                        summary = type(obj).__name__ if obj is not None \
                            else "(undecoded)"
                        self._recent_messages.append((env.descriptor, summary))
                        if len(self._recent_messages) > 200:
                            self._recent_messages = \
                                self._recent_messages[-200:]
                    if self.monitor is not None:
                        self.monitor.emit("uxas_in",
                                          type(obj).__name__ if obj is not None
                                                              else "(undecoded)",
                                          _summarise_lmcp(obj) if obj is not None
                                                              else env.descriptor,
                                          extra={"descriptor": env.descriptor})
                    for cb in self._callbacks:
                        try:
                            cb(env, obj)
                        except Exception as exc:
                            print(f"[UxAS] Callback error: {exc}")
            except zmq.ZMQError:
                if self._running:
                    time.sleep(0.1)
            except Exception as exc:
                if self._running:
                    print(f"[UxAS] Receive error: {exc}")
                    time.sleep(0.5)


# ---------------------------------------------------------------------------
# Bridge core
# ---------------------------------------------------------------------------

class QGCUxASBridge:
    """Orchestrates MAVLink <-> LMCP/ZMQ traffic."""

    DEFAULT_STATE_RATE_HZ = 2.0

    def __init__(self, mavlink_str: str, uxas_pub: str, uxas_pull: str,
                 vehicle_id: int = 1,
                 state_rate_hz: float = DEFAULT_STATE_RATE_HZ,
                 require_heartbeat: bool = True,
                 vehicle_label: str = "",
                 capability: Optional[dict] = None,
                 alt_takeover_agl_m: float = 200.0,
                 auto_arm_on_start: bool = False,
                 auto_arm_min_alt_agl_m: float = 0.0,
                 auto_takeoff_agl_m: float = 0.0,
                 monitor_port: int = 0,
                 monitor_host: str = "127.0.0.1"):
        self.vehicle_id = vehicle_id
        self.state_rate_hz = state_rate_hz
        self.vehicle_label = vehicle_label or f"Vehicle_{vehicle_id}"
        # capability fields populate AirVehicleConfiguration on register_vehicle.
        # Keys: min_speed, max_speed, nominal_speed, nominal_alt,
        #       min_alt, max_alt, max_climb, max_bank_deg.
        self.capability = dict(capability or {})

        # Optional QGC monitor tap (per-message UDP JSON to MessageMonitorPage).
        self.monitor: Optional[MonitorTap] = (
            MonitorTap(host=monitor_host, port=monitor_port,
                       vehicle_id=vehicle_id)
            if monitor_port > 0 else None
        )

        self.mavlink = MAVLinkReader(mavlink_str, vehicle_id=vehicle_id,
                                     require_heartbeat=require_heartbeat)
        self.uxas = UxASInterface(sub_addr=uxas_pub, push_addr=uxas_pull,
                                  entity_id=vehicle_id, service_id=0,
                                  monitor=self.monitor)

        self._running = False
        self._state_thread: Optional[threading.Thread] = None
        self._takeover_thread: Optional[threading.Thread] = None
        self._registered = False
        self._task_counter = 100
        self._request_counter = 1000

        # Mission takeover logic
        self._alt_takeover_agl_m = alt_takeover_agl_m
        self._pending_mission_command: Any = None
        self._mission_lock = threading.Lock()
        self._mission_active = False

        # Auto-arm logic (for air-spawn fixed-wing)
        self._auto_arm = auto_arm_on_start
        self._auto_arm_min_alt = auto_arm_min_alt_agl_m
        self._auto_armed = False

        # Auto-takeoff (multicopter / ground-spawn vehicles)
        # When > 0, bridge arms and issues NAV_TAKEOFF at startup so vehicle
        # climbs to the given AGL altitude without operator input.
        self._auto_takeoff_agl_m = auto_takeoff_agl_m
        self._takeoff_initiated = False

    def start(self) -> None:
        self.mavlink.start()
        self.uxas.start()
        self.uxas.on_message(self._handle_uxas_message)

        self._running = True
        self._state_thread = threading.Thread(
            target=self._state_publish_loop, daemon=True,
            name="state-publisher")
        self._state_thread.start()
        self._takeover_thread = threading.Thread(
            target=self._takeover_loop, daemon=True, name="takeover")
        self._takeover_thread.start()
        extras = []
        if self._auto_arm: extras.append("auto-arm")
        if self._auto_takeoff_agl_m > 0:
            extras.append(f"auto-takeoff@{self._auto_takeoff_agl_m:.0f}m")
        extras_str = (", " + ", ".join(extras)) if extras else ""
        print(f"[Bridge] Running (vehicle_id={self.vehicle_id}, "
              f"state rate={self.state_rate_hz} Hz, "
              f"takeover@{self._alt_takeover_agl_m:.0f}m AGL"
              f"{extras_str})")

    def stop(self) -> None:
        self._running = False
        if self._state_thread:
            self._state_thread.join(timeout=3)
        if self._takeover_thread:
            self._takeover_thread.join(timeout=3)
        self.uxas.stop()
        self.mavlink.stop()
        if self.monitor is not None:
            self.monitor.close()
        print("[Bridge] Stopped")

    def register_vehicle(self) -> None:
        cap = self.capability
        avc = build_air_vehicle_configuration(
            vehicle_id=self.vehicle_id,
            label=self.vehicle_label,
            min_speed=cap.get("min_speed", 5.0),
            max_speed=cap.get("max_speed", 30.0),
            nominal_speed=cap.get("nominal_speed"),
            nominal_altitude=cap.get("nominal_alt", 100.0),
            max_climb=cap.get("max_climb", 5.0),
            min_alt=cap.get("min_alt", 0.0),
            max_alt=cap.get("max_alt", 500.0),
            max_bank_deg=cap.get("max_bank_deg", 25.0),
        )
        self.uxas.publish(avc)
        self._registered = True
        print(f"[Bridge] Vehicle {self.vehicle_id} ({self.vehicle_label}) "
              f"registered with UxAS "
              f"[speed {cap.get('min_speed', 5.0):.0f}-{cap.get('max_speed', 30.0):.0f} m/s, "
              f"alt {cap.get('min_alt', 0.0):.0f}-{cap.get('max_alt', 500.0):.0f} m]")

    def send_area_search(self,
                         area: list[tuple[float, float]],
                         altitude: float = 50.0) -> int:
        task_id = self._next_task_id()
        task = build_area_search_task(
            task_id=task_id, polygon_lat_lon=area,
            eligible_vehicles=[self.vehicle_id],
            altitude_m=altitude)
        self.uxas.publish(task)
        print(f"[Bridge] AreaSearchTask {task_id} sent")

        req = build_automation_request(
            request_id=self._next_request_id(),
            task_ids=[task_id],
            vehicle_ids=[self.vehicle_id])
        self.uxas.publish(req)
        print(f"[Bridge] AutomationRequest sent for task {task_id}")
        return task_id

    def send_line_search(self,
                         points: list[tuple[float, float]],
                         altitude: float = 50.0) -> int:
        task_id = self._next_task_id()
        task = build_line_search_task(
            task_id=task_id, line_lat_lon=points,
            eligible_vehicles=[self.vehicle_id],
            altitude_m=altitude)
        self.uxas.publish(task)
        print(f"[Bridge] LineSearchTask {task_id} sent")

        req = build_automation_request(
            request_id=self._next_request_id(),
            task_ids=[task_id],
            vehicle_ids=[self.vehicle_id])
        self.uxas.publish(req)
        print(f"[Bridge] AutomationRequest sent for task {task_id}")
        return task_id

    def get_status(self) -> dict:
        state = self.mavlink.get_state()
        return {
            "vehicle_id": self.vehicle_id,
            "registered": self._registered,
            "running": self._running,
            "vehicle_state": {
                "lat": state.lat_deg, "lon": state.lon_deg,
                "alt": state.alt_m, "heading": state.heading_deg,
                "airspeed": state.airspeed_mps,
                "groundspeed": state.groundspeed_mps,
                "mode": state.mode, "armed": state.armed,
                "battery": state.battery_pct,
            },
            "stats": {
                "mavlink_in": self.mavlink.stats.mavlink_msgs_in,
                "mavlink_out": self.mavlink.stats.mavlink_msgs_out,
                "lmcp_in": self.uxas.stats.lmcp_msgs_in,
                "lmcp_out": self.uxas.stats.lmcp_msgs_out,
                "missions_uploaded": self.mavlink.stats.missions_uploaded,
                "errors": (self.mavlink.stats.errors
                           + self.uxas.stats.errors),
                "uptime_s": round(
                    time.monotonic() - self.mavlink.stats.start_time, 1),
            },
            "recent_lmcp": self.uxas.get_recent(5),
        }

    # ------------------------------------------------------------------ inner

    def _next_task_id(self) -> int:
        self._task_counter += 1
        return self._task_counter

    def _next_request_id(self) -> int:
        self._request_counter += 1
        return self._request_counter

    def _state_publish_loop(self) -> None:
        interval = 1.0 / self.state_rate_hz
        while self._running:
            try:
                state = self.mavlink.get_state()
                if state.timestamp_ms == 0:
                    time.sleep(interval)
                    continue
                avs = build_air_vehicle_state(state)
                self.uxas.publish(avs)
            except Exception as exc:
                print(f"[Bridge] State publish error: {exc}")
            time.sleep(interval)

    def _handle_uxas_message(self, env: Envelope, obj: Any) -> None:
        if obj is None:
            return
        cls_name = type(obj).__name__
        if cls_name == "MissionCommand":
            self._handle_mission_command(obj)
        elif cls_name == "AutomationResponse":
            # UxAS delivers the planned route(s) INSIDE the AutomationResponse
            # (MissionCommandList) — it does not also broadcast standalone
            # MissionCommand messages in this configuration. Extract and route
            # each embedded MissionCommand the same way as a standalone one.
            mcs = getattr(obj, "MissionCommandList", None) or []
            print(f"[Bridge] Received AutomationResponse from UxAS "
                  f"({len(mcs)} MissionCommand(s))")
            for mc in mcs:
                if mc is not None:
                    self._handle_mission_command(mc)
        else:
            # Quiet by default; log unfamiliar messages at debug level
            pass

    def _handle_mission_command(self, mc) -> None:
        target_id = 0
        try:
            target_id = mc.get_VehicleID()
        except Exception:
            pass
        if target_id and target_id != self.vehicle_id:
            return  # not for us

        wps = waypoints_from_mission_command(mc)
        if not wps:
            print("[Bridge] MissionCommand had no waypoints")
            return

        s = self.mavlink.get_state()
        if s.alt_agl_m < self._alt_takeover_agl_m or not s.armed:
            with self._mission_lock:
                self._pending_mission_command = mc
            print(f"[Bridge] MissionCommand cached "
                  f"(waiting for armed && alt_agl >= "
                  f"{self._alt_takeover_agl_m:.0f} m, current "
                  f"armed={s.armed} agl={s.alt_agl_m:.1f} m)")
            return

        self._activate_mission(mc)

    def _activate_mission(self, mc) -> None:
        wps = waypoints_from_mission_command(mc)
        # Yaw each waypoint along the direction of travel so the airframe (and
        # a heading-mounted camera) points where it is going. PX4 adopts the
        # ACTIVE waypoint's param4 while flying the leg INTO it, so waypoint N
        # must carry the bearing of the incoming leg (N-1 → N), not the
        # outgoing one. The first waypoint has no incoming leg, so it borrows
        # the first outgoing bearing.
        items = []
        for i, wp in enumerate(wps):
            prev = wps[i - 1] if i > 0 else None
            if prev is not None:
                yaw_deg = _bearing_deg(prev.lat_deg, prev.lon_deg,
                                       wp.lat_deg, wp.lon_deg)
            elif len(wps) > 1:
                yaw_deg = _bearing_deg(wp.lat_deg, wp.lon_deg,
                                       wps[1].lat_deg, wps[1].lon_deg)
            else:
                yaw_deg = 0.0
            items.append({
                "frame": 6,  # MAV_FRAME_GLOBAL_RELATIVE_ALT_INT
                "command": 16,  # MAV_CMD_NAV_WAYPOINT
                "autocontinue": 1, "param1": 0, "param2": 5.0,
                "param3": 0, "param4": yaw_deg,
                "lat": wp.lat_deg, "lon": wp.lon_deg, "alt": wp.alt_m,
            })
        # PX4 fixed-wing rejects AUTO.MISSION without a landing (MIS_TKO_LAND_REQ).
        # Append a NAV_LAND at the last search waypoint so the mission is valid
        # for both fixed-wing and multicopter (a rough "land where you finished").
        if items:
            last = items[-1]
            alt_L = max(50.0, float(last.get("alt", 0.0)))
            # Bearing of the final leg (so the touchdown extends straight ahead).
            if len(items) >= 2:
                brg = _bearing_deg(items[-2]["lat"], items[-2]["lon"],
                                   last["lat"], last["lon"])
            else:
                brg = 0.0
            # Push the touchdown point downrange for a gentle ~6° glide; PX4's
            # fixed-wing landing rejects approaches steeper than ~8°, so placing
            # NAV_LAND at the last waypoint (near-vertical descent) is refused.
            glide_d = max(500.0, alt_L / math.tan(math.radians(6.0)))
            brg_rad = math.radians(brg)
            lat_land = last["lat"] + _meters_to_lat(glide_d * math.cos(brg_rad))
            lon_land = last["lon"] + _meters_to_lon(glide_d * math.sin(brg_rad),
                                                    last["lat"])
            items.append({
                "frame": 6,  # MAV_FRAME_GLOBAL_RELATIVE_ALT_INT
                "command": 21,  # MAV_CMD_NAV_LAND
                "autocontinue": 1, "param1": 0, "param2": 0,
                "param3": 0, "param4": float('nan'),
                "lat": lat_land, "lon": lon_land, "alt": 0,
            })
        print(f"[Bridge] Activating UxAS mission ({len(items)} waypoints, "
              f"incl. landing) on vehicle {self.vehicle_id}")
        # Dump the converted mission for offline analysis (issue: vehicle
        # entered AUTO.MISSION but immediately reported COMPLETE/LOITER).
        try:
            dump_dir = os.path.join(_SCRIPT_DIR, "..", "logs")
            os.makedirs(dump_dir, exist_ok=True)
            dump_path = os.path.join(
                dump_dir, f"mission_dump_v{self.vehicle_id}_"
                          f"{int(time.time())}.json")
            with open(dump_path, "w") as fh:
                json.dump({
                    "vehicle_id": self.vehicle_id,
                    "first_waypoint": getattr(mc, "get_FirstWaypoint",
                                              lambda: None)(),
                    "waypoint_numbers": [
                        wp.get_Number() for wp in mc.get_WaypointList()],
                    "next_waypoints": [
                        wp.get_NextWaypoint() for wp in mc.get_WaypointList()],
                    "items": items,
                }, fh, indent=1)
            print(f"[Bridge] Mission dumped to {dump_path}")
            for it in items[:3] + items[-2:]:
                print(f"[Bridge]   wp ({it['lat']:.6f},{it['lon']:.6f}) "
                      f"alt={it['alt']:.1f}")
        except Exception as exc:
            print(f"[Bridge] Mission dump failed: {exc}")
        ok = self.mavlink.upload_mission(items)
        if not ok:
            print(f"[Bridge] Failed to upload mission to vehicle "
                  f"{self.vehicle_id}")
            return
        if self.mavlink.set_mode_auto_mission():
            # Defense in depth: verify the mode actually stuck. If PX4
            # bounced back to LOITER (e.g. mode change raced another auto
            # mode), re-command once — a second activation resets the
            # navigator's finished flag and the mission executes normally.
            for _ in range(5):
                time.sleep(1.0)
                if self.mavlink.get_state().mode == "auto_mission":
                    break
            else:
                print(f"[Bridge] AUTO.MISSION did not stick "
                      f"(mode={self.mavlink.get_state().mode}) — re-commanding")
                self.mavlink.set_mode_auto_mission()
            self._mission_active = True
            print(f"[Bridge] Vehicle {self.vehicle_id} entered AUTO.MISSION")

    def _takeover_loop(self) -> None:
        """Monitor altitude + arm state; auto-arm air-spawn vehicles and
        activate cached UxAS missions once the vehicle is high enough."""
        announced_ready = False
        while self._running:
            time.sleep(1.0)
            s = self.mavlink.get_state()

            # Auto-arm (air-spawn fixed-wing)
            if (self._auto_arm and not self._auto_armed and not s.armed
                    and s.alt_agl_m >= self._auto_arm_min_alt
                    and s.gps_fix >= 3):
                print(f"[Bridge] Auto-arm: agl={s.alt_agl_m:.1f}m gps_fix={s.gps_fix}")
                if self.mavlink.arm(True):
                    self._auto_armed = True
                    # Cessna needs cruise stabilization first → wait a bit then
                    # switch to AUTO.MISSION so the existing throttle ramp
                    # doesn't fight a fresh mode change.
                    threading.Thread(
                        target=self._delayed_auto_mission,
                        args=(3.0,), daemon=True).start()

            # Auto-takeoff (ground-spawn multicopter)
            if (self._auto_takeoff_agl_m > 0 and not self._takeoff_initiated
                    and not s.armed and s.gps_fix >= 3
                    and s.alt_agl_m < 5.0):
                print(f"[Bridge] Auto-takeoff sequence: arm + TAKEOFF to "
                      f"{self._auto_takeoff_agl_m:.0f}m AGL")
                if self.mavlink.arm(True):
                    time.sleep(1.0)
                    if self.mavlink.takeoff(self._auto_takeoff_agl_m):
                        self._takeoff_initiated = True
                    else:
                        # Roll back arm so we can retry next iteration
                        self.mavlink.arm(False)

            # Activate cached mission when ready.
            # NOTE: must NOT activate while AUTO.TAKEOFF is still running.
            # The takeover altitude (200 m) is below the takeoff target
            # (220 m), so the threshold always crosses mid-takeoff; switching
            # to AUTO.MISSION at that moment makes the PX4 navigator mark the
            # fresh mission finished without flying it (mission_result
            # finished=True, seq_reached=-1) and fall back to AUTO.LOITER.
            # Waiting for the takeoff mode to end fixes the race.
            with self._mission_lock:
                pending = self._pending_mission_command
            if pending is not None and s.armed \
                    and s.alt_agl_m >= self._alt_takeover_agl_m \
                    and s.mode != "auto_takeoff":
                with self._mission_lock:
                    self._pending_mission_command = None
                print(f"[Bridge] Vehicle {self.vehicle_id} reached "
                      f"{s.alt_agl_m:.1f} m AGL — activating UxAS mission")
                self._activate_mission(pending)
            elif pending is not None and not announced_ready and s.armed:
                announced_ready = True
                print(f"[Bridge] Vehicle {self.vehicle_id} armed, climb to "
                      f"{self._alt_takeover_agl_m:.0f} m AGL to trigger "
                      f"UxAS mission")

    def _delayed_auto_mission(self, delay_s: float) -> None:
        time.sleep(delay_s)
        if self._running:
            self.mavlink.set_mode_auto_mission()


# ---------------------------------------------------------------------------
# Interactive CLI
# ---------------------------------------------------------------------------

class BridgeCLI(cmd.Cmd):
    intro = textwrap.dedent("""
        QGC <-> OpenUxAS Bridge CLI
        Type 'help' for available commands.
    """)
    prompt = "bridge> "

    def __init__(self, bridge: QGCUxASBridge):
        super().__init__()
        self.bridge = bridge

    def do_register(self, arg: str) -> None:
        """Register the vehicle with UxAS (sends AirVehicleConfiguration)."""
        self.bridge.register_vehicle()

    def do_area_search(self, arg: str) -> None:
        """area_search lat1,lon1 lat2,lon2 lat3,lon3 [lat4,lon4 ...] [alt]"""
        area, alt = self._parse_points_and_alt(arg, min_points=3)
        if area is None:
            return
        tid = self.bridge.send_area_search(area, altitude=alt)
        print(f"AreaSearch task {tid} submitted")

    def do_line_search(self, arg: str) -> None:
        """line_search lat1,lon1 lat2,lon2 [lat3,lon3 ...] [alt]"""
        pts, alt = self._parse_points_and_alt(arg, min_points=2)
        if pts is None:
            return
        tid = self.bridge.send_line_search(pts, altitude=alt)
        print(f"LineSearch task {tid} submitted")

    def do_status(self, arg: str) -> None:
        """Show bridge status, message counters, vehicle state."""
        print(json.dumps(self.bridge.get_status(), indent=2))

    def do_state(self, arg: str) -> None:
        """Show current vehicle state."""
        s = self.bridge.mavlink.get_state()
        info = {
            "vehicle_id": s.vehicle_id,
            "position": f"({s.lat_deg:.7f}, {s.lon_deg:.7f})",
            "altitude_m": f"{s.alt_m:.1f}",
            "heading_deg": f"{s.heading_deg:.1f}",
            "airspeed_mps": f"{s.airspeed_mps:.1f}",
            "groundspeed_mps": f"{s.groundspeed_mps:.1f}",
            "mode": s.mode, "armed": s.armed,
            "battery_pct": f"{s.battery_pct:.0f}",
        }
        for k, v in info.items():
            print(f"  {k:18s}: {v}")

    def do_messages(self, arg: str) -> None:
        """Show recent LMCP message types received from UxAS."""
        n = int(arg) if arg.strip().isdigit() else 10
        for descriptor, summary in self.bridge.uxas.get_recent(n):
            print(f"  {descriptor:50s} -> {summary}")

    def do_quit(self, arg: str) -> bool:
        """Exit the bridge CLI."""
        return True

    do_exit = do_quit
    do_EOF = do_quit

    def _parse_points_and_alt(self, arg: str, min_points: int):
        parts = arg.split()
        pts: list[tuple[float, float]] = []
        alt = 50.0
        for p in parts:
            if "," in p:
                try:
                    a, b = p.split(",")
                    pts.append((float(a), float(b)))
                except ValueError:
                    pass
            else:
                try:
                    alt = float(p)
                except ValueError:
                    pass
        if len(pts) < min_points:
            print(f"need at least {min_points} 'lat,lon' points")
            return None, None
        return pts, alt


# ---------------------------------------------------------------------------
# CLI entry point
# ---------------------------------------------------------------------------

def _build_parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(
        description="QGC (MAVLink) <-> OpenUxAS (LMCP/ZeroMQ) Bridge",
    )
    p.add_argument("--mavlink", default="udp:127.0.0.1:14550",
                   help="MAVLink connection string "
                        "(default: udp:127.0.0.1:14550)")
    p.add_argument("--uxas-pub", default="tcp://127.0.0.1:5560",
                   help="UxAS external PUB socket address (we SUB to it). "
                        "Default: tcp://127.0.0.1:5560")
    p.add_argument("--uxas-pull", default="tcp://127.0.0.1:5561",
                   help="UxAS external PULL socket address (we PUSH to it). "
                        "Default: tcp://127.0.0.1:5561")
    p.add_argument("--vehicle-id", type=int, default=1,
                   help="Vehicle ID for LMCP messages (default: 1)")
    p.add_argument("--state-rate", type=float, default=2.0,
                   help="AirVehicleState publish rate (Hz, default: 2.0)")
    p.add_argument("--auto-register", action="store_true",
                   help="Send AirVehicleConfiguration on startup")
    p.add_argument("--non-interactive", action="store_true",
                   help="Run without an interactive CLI")
    p.add_argument("--no-heartbeat-wait", action="store_true",
                   help="Skip waiting for a MAVLink heartbeat "
                        "(for offline/UxAS-only checks)")
    p.add_argument("--label", default="",
                   help="LMCP AirVehicleConfiguration label "
                        "(default: Vehicle_<id>)")
    p.add_argument("--min-speed", type=float, default=5.0,
                   help="LMCP MinimumSpeed m/s (multicopter=0, fixedwing>0)")
    p.add_argument("--max-speed", type=float, default=30.0,
                   help="LMCP MaximumSpeed m/s")
    p.add_argument("--nominal-speed", type=float, default=None,
                   help="LMCP NominalSpeed m/s (default: (min+max)/2)")
    p.add_argument("--min-alt", type=float, default=0.0,
                   help="LMCP min altitude m (multicopter=0, fixedwing>~20)")
    p.add_argument("--max-alt", type=float, default=500.0,
                   help="LMCP max altitude m")
    p.add_argument("--nominal-alt", type=float, default=100.0,
                   help="LMCP nominal altitude m")
    p.add_argument("--max-climb", type=float, default=5.0,
                   help="LMCP MaximumClimbRate m/s")
    p.add_argument("--max-bank-deg", type=float, default=25.0,
                   help="LMCP MaxBankAngle deg")
    p.add_argument("--alt-takeover-agl", type=float, default=200.0,
                   help="UxAS plan takeover threshold (m AGL, default 200)")
    p.add_argument("--auto-arm-on-start", action="store_true",
                   help="Bridge auto-arms once GPS-fixed and above "
                        "--auto-arm-min-alt (use for air-spawn fixed-wing)")
    p.add_argument("--auto-arm-min-alt", type=float, default=0.0,
                   help="Minimum alt_agl_m for auto-arm trigger "
                        "(default 0: arm as soon as GPS fix is acquired)")
    p.add_argument("--auto-takeoff-agl", type=float, default=0.0,
                   help="If > 0, bridge auto-arms and issues NAV_TAKEOFF to "
                        "this AGL altitude (multicopter / ground-spawn use). "
                        "Default 0: disabled.")
    p.add_argument("--monitor-port", type=int, default=0,
                   help="If > 0, fire-and-forget JSON LMCP summaries to this "
                        "UDP port on --monitor-host (default 127.0.0.1). QGC's "
                        "MessageMonitorPage listens on 45680. Use 0 to "
                        "disable (default).")
    p.add_argument("--monitor-host", default="127.0.0.1",
                   help="Destination host for --monitor-port (default 127.0.0.1)")
    p.add_argument("--camera-fov", type=float, default=45.0,
                   help="Initial camera horizontal FOV (deg) streamed to UxAS; "
                        "auto-updated from QGC panel publishes on 45678 (default 45)")
    p.add_argument("--px4-param", action="append", default=[],
                   metavar="NAME=VALUE",
                   help="PX4 parameter to apply via MAVLink PARAM_SET after "
                        "connecting (repeatable). launch_bridges.sh fills "
                        "these from vehicles.json \"parameters\".")
    return p


def main(argv: Optional[list[str]] = None) -> int:
    args = _build_parser().parse_args(argv)

    # Camera FOV default; the live value tracks the QGC panel via _FOV_FILE,
    # which the UxAS search listener writes on each publish (no port contention).
    _CAMERA_FOV[0] = args.camera_fov

    capability = {
        "min_speed": args.min_speed,
        "max_speed": args.max_speed,
        "nominal_speed": args.nominal_speed,
        "min_alt": args.min_alt,
        "max_alt": args.max_alt,
        "nominal_alt": args.nominal_alt,
        "max_climb": args.max_climb,
        "max_bank_deg": args.max_bank_deg,
    }
    bridge = QGCUxASBridge(
        mavlink_str=args.mavlink,
        uxas_pub=args.uxas_pub,
        uxas_pull=args.uxas_pull,
        vehicle_id=args.vehicle_id,
        state_rate_hz=args.state_rate,
        require_heartbeat=not args.no_heartbeat_wait,
        vehicle_label=args.label,
        capability=capability,
        alt_takeover_agl_m=args.alt_takeover_agl,
        auto_arm_on_start=args.auto_arm_on_start,
        auto_arm_min_alt_agl_m=args.auto_arm_min_alt,
        auto_takeoff_agl_m=args.auto_takeoff_agl,
        monitor_port=args.monitor_port,
        monitor_host=args.monitor_host,
    )

    def signal_handler(signum, frame):
        print(f"\n[Bridge] Signal {signum} received -- shutting down")
        bridge.stop()
        sys.exit(0)

    signal.signal(signal.SIGINT, signal_handler)
    signal.signal(signal.SIGTERM, signal_handler)

    try:
        bridge.start()
        for spec in args.px4_param:
            name, sep, raw = spec.partition("=")
            if not sep:
                print(f"[Bridge] Ignoring malformed --px4-param {spec!r}")
                continue
            try:
                value = float(raw)
            except ValueError:
                print(f"[Bridge] Ignoring non-numeric --px4-param {spec!r}")
                continue
            bridge.mavlink.set_param(name.strip(), value)
        if args.auto_register:
            time.sleep(1.0)  # let connections stabilize
            bridge.register_vehicle()

        if args.non_interactive:
            print("[Bridge] Running in non-interactive mode. Ctrl+C to stop.")
            while True:
                time.sleep(1)
        else:
            BridgeCLI(bridge).cmdloop()
    except KeyboardInterrupt:
        pass
    finally:
        bridge.stop()
    return 0


if __name__ == "__main__":
    sys.exit(main())
